{% set name = "PyMySQL" %}
{% set version = "1.1.2" %}
{% set sha256 = "dffceb6354556d48161005ede20374d312ac0f52d8db51ee007974866c8351a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PyMySQL/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pymysql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/PyMySQL/PyMySQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python MySQL Driver
  description: |
    This package contains a pure-Python MySQL client library. The goal of
    PyMySQL is to be a drop-in replacement for MySQLdb and work on CPython,
    PyPy and IronPython.
  doc_url: http://pymysql.readthedocs.io/
  dev_url: https://github.com/PyMySQL/PyMySQL

extra:
  recipe-maintainers:
    - djsutherland
    - synapticarbors
    - thewchan
